version: "3.9"

services:
  web:
    build: .
    command:
      - bash
      - -c
      - |
        /code/manage.py makemigrations && /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-network
    restart:
      unless-stopped


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - my-network

  celery:
    build: .
    command: celery -A webhook worker -l info
    volumes:
      - .:/code
    depends_on:
      - beat
    networks:
      - my-network
    restart: unless-stopped

  beat:
    build: .
    command: celery -A webhook beat -l info
    volumes:
      - .:/code
    networks:
      - my-network
    restart: unless-stopped

  redis:
    image: redis:latest
    networks:
      - my-network
    mem_limit: 1024m
    restart: unless-stopped

volumes:
  postgres_data:

networks:
    my-network: