version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.12
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env
    command: rabbitmq-server --plugins rabbitmq_management

volumes:
  rabbitmq_data:
