# Generated by Django 3.2.18 on 2023-06-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedCoinTransaction',
            fields=[
                ('confirmedtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trc20webhook.confirmedtransaction')),
                ('coin_amount', models.CharField(max_length=100)),
            ],
            bases=('trc20webhook.confirmedtransaction',),
        ),
        migrations.CreateModel(
            name='ConfirmedTokenTransaction',
            fields=[
                ('confirmedtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trc20webhook.confirmedtransaction')),
                ('toke_type', models.CharField(max_length=10)),
                ('token_name', models.CharField(max_length=100)),
                ('token_symbol', models.CharField(max_length=10)),
                ('token_amount', models.CharField(max_length=100)),
                ('decimals', models.CharField(max_length=100)),
            ],
            bases=('trc20webhook.confirmedtransaction',),
        ),
    ]
