# Generated by Django 4.2.2 on 2023-07-02 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trc20webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_block_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('decimals', models.IntegerField(verbose_name='decimals')),
                ('contract_address', models.CharField(blank=True, max_length=100)),
                ('abi', models.TextField(blank=True)),
                ('parse', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('NTV', 'Native'), ('CNT', 'Contract')], max_length=3)),
                ('creator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=8)),
                ('deposit_enabled', models.BooleanField(default=False)),
                ('withdrawal_enabled', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('WB3', 'Web3'), ('BTC', 'BtcFork'), ('API', 'API')], max_length=3)),
                ('creator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction_type', models.CharField(default='withdrawal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.coin')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.network')),
            ],
            options={
                'db_table': 'transaction_history_{wallet_id}',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('creator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='confirmedtokentransaction',
            name='confirmedtransaction_ptr',
        ),
        migrations.DeleteModel(
            name='ConfirmedCoinTransaction',
        ),
        migrations.DeleteModel(
            name='ConfirmedTokenTransaction',
        ),
        migrations.DeleteModel(
            name='ConfirmedTransaction',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.wallet'),
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.network'),
        ),
        migrations.AddField(
            model_name='block',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trc20webhook.network'),
        ),
    ]
