# Generated by Django 4.2.2 on 2023-07-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trc20webhook', '0002_block_coin_network_transactionhistory_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='timestamp',
            field=models.DateTimeField(default=''),
        ),
    ]
