# Generated by Django 4.2.2 on 2023-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trc20webhook', '0003_alter_transactionhistory_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('transaction_hash', 'network')},
        ),
    ]
